import type { Guest } from "./types";

const accepted = "accepted" as const;
const pending = "pending" as const;

export const guests: Guest[] = [
    { name: "Shane Wade", table: "Sweetheart", rsvp: accepted },
    { name: "Aileen Duong", table: "Sweetheart", rsvp: accepted },
    { name: "Heng Duong", table: 1, rsvp: accepted },
    { name: "Siv Ngoy", table: 1, rsvp: accepted },
    { name: "Niy Pierce", table: 1, rsvp: accepted },
    { name: "Lonnie Pierce", table: 1, rsvp: accepted },
    { name: "Don Wade", table: 1, rsvp: accepted },
    { name: "John Wade", table: 1, rsvp: accepted },
    { name: "Paul Wade", table: 1, rsvp: accepted, glutenFree: true },
    { name: "Jami Spencer", table: 1, rsvp: accepted, glutenFree: true },
    { name: "Jake Galvan", table: 2, rsvp: accepted },
    { name: "Mireille Galvan", table: 2, rsvp: accepted },
    { name: "Grace Galvan", table: 2, rsvp: accepted },
    { name: "Shannon Wade", table: 2, rsvp: accepted },
    { name: "Josh Wade", table: 2, rsvp: accepted },
    { name: "Janine Wade", table: 2, rsvp: accepted },
    { name: "Shellee Spencer", table: 2, rsvp: accepted },
    { name: "Carrie Fonda", table: 2, rsvp: accepted },
    { name: "Steve Yamarone", table: 3, rsvp: accepted },
    { name: "Michelle Yamarone", table: 3, rsvp: accepted },
    { name: "Tony Yamarone", table: 3, rsvp: accepted },
    { name: "Carley Yamarone", table: 3, rsvp: accepted },
    { name: "Carter Yamarone", table: 3, rsvp: accepted },
    { name: "Landon Yamarone", table: 3, rsvp: accepted },
    { name: "Luke Wade", table: 3, rsvp: accepted },
    { name: "Natalie Nichols", table: 3, rsvp: accepted },
    { name: "Alex Rodrigues", table: 4, rsvp: accepted },
    { name: "Anastasia Miron", table: 4, rsvp: accepted },
    { name: "Jill Rodrigues", table: 4, rsvp: accepted },
    { name: "Claudio Rodrigues", table: 4, rsvp: accepted, glutenFree: true },
    { name: "Ahmed Beshry", table: 4, rsvp: accepted },
    { name: "Brandon Moak", table: 4, rsvp: accepted },
    { name: "Mac Hunik", table: 4, rsvp: accepted, glutenFree: true },
    { name: "Matt Woodland", table: 4, rsvp: accepted },
    { name: "Marcus Sjolin", table: 4, rsvp: accepted },
    { name: "Danette Kha", table: 5, rsvp: accepted },
    { name: "Muuduu Otgonbold", table: 5, rsvp: accepted },
    { name: "Alex Smith", table: 5, rsvp: accepted },
    { name: "Jeremy Rice", table: 5, rsvp: accepted },
    { name: "Analee Scott", table: 5, rsvp: accepted },
    { name: "Tim Cumagun", table: 5, rsvp: accepted },
    { name: "Jodie Scott", table: 5, rsvp: accepted },
    { name: "Alex Jacobsen", table: 5, rsvp: accepted },
    { name: "Lauren Kercheval", table: 5, rsvp: accepted },
    { name: "Calin Drimbau", table: 5, rsvp: accepted },
    { name: "Eric Sebastiani", table: 5, rsvp: accepted },
    { name: "Marianne Cruzat", table: 6, rsvp: accepted },
    { name: "Patrick Bacon", table: 6, rsvp: accepted },
    { name: "Paul Ashbourne", table: 6, rsvp: accepted },
    { name: "Frida Vizcaino", table: 6, rsvp: accepted, glutenFree: true },
    { name: "Kote Mushegiani", table: 6, rsvp: accepted },
    { name: "Stevi Dunn", table: 6, rsvp: accepted, glutenFree: true },
    { name: "Jade Tuan", table: 6, rsvp: accepted },
    { name: "Anish Chopra", table: 6, rsvp: accepted },
    { name: "Aditya Patil", table: 6, rsvp: accepted },
    { name: "Mimi Yen", table: 6, rsvp: accepted },
    { name: "Taylor England", table: 7, rsvp: pending },
    { name: "Liam Benson", table: 7, rsvp: pending },
    { name: "Rena Lu", table: 7, rsvp: accepted },
    { name: "Stefan Zhu", table: 7, rsvp: accepted },
    { name: "Sepehr Fard", table: 7, rsvp: accepted },
    { name: "Henry Su", table: 7, rsvp: accepted },
    { name: "Michelle Nguyen", table: 7, rsvp: accepted },
    { name: "David Head", table: 7, rsvp: accepted, glutenFree: true },
    { name: "Eileen Li", table: 7, rsvp: accepted },
    { name: "", table: "", rsvp: accepted },
    { name: "", table: "", rsvp: accepted },
    { name: "", table: "", rsvp: accepted },
    { name: "", table: "", rsvp: accepted },
];
